version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ./db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_MULTIPLE_DATABASES=rms_users,rms_users: rms_media_discovery,rms_media_discovery: rms_bot_server,rms_bot_server"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qweasd123
      
  media-discovery:
    image: racoonmediaserver/media-discovery:latest
    restart: always
    container_name: media-discovery
    environment:
      - RMS_DATABASE_HOST=db
      - RMS_DATABASE_DATABASE=rms_media_discovery
      - RMS_DATABASE_USER=postgres
      - RMS_DATABASE_PASSWORD=qweasd123
      - RMS_HTTP_HOST=0.0.0.0
      - RMS_MONITOR_HOST=0.0.0.0
      - MICRO_REGISTRY=mdns
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db
      - users

  users:
    image: racoonmediaserver/users:latest
    restart: always
    container_name: users
    environment:
      - RMS_DATABASE_HOST=db
      - RMS_DATABASE_DATABASE=rms_users
      - RMS_DATABASE_USER=postgres
      - RMS_DATABASE_PASSWORD=qweasd123
      - RMS_HTTP_HOST=0.0.0.0
      - RMS_MONITOR_HOST=0.0.0.0
      - MICRO_REGISTRY=mdns
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db

  bot:
    image: racoonmediaserver/bot-server:latest
    restart: always
    container_name: bot
    environment:
      - RMS_DATABASE_HOST=db
      - RMS_DATABASE_DATABASE=rms_bot_server
      - RMS_DATABASE_USER=postgres
      - RMS_DATABASE_PASSWORD=qweasd123
      - RMS_BOT_TOKEN=
      - RMS_HTTP_HOST=0.0.0.0
      - RMS_MONITOR_HOST=0.0.0.0
      - MICRO_REGISTRY=mdns
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db
      - users
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - media-discovery
      - users
      - bot

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "127.0.0.1:9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    links:
      - prometheus

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

